# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0008_auto_20170605_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
