# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0009_auto_20170605_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinfo',
            name='prev_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_prev_club', to='introduction_to_models.Club'),
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_recommender', to='introduction_to_models.Player'),
        ),
        migrations.AlterField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(related_name='introduction_to_models_club_related', through='introduction_to_models.TradeInfo', to='introduction_to_models.Player'),
        ),
    ]
