# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0013_student_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='introduction_to_models_abc_teacher',
        ),
    ]
